/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import Commands.DefaultCommand;
import Commands.PersonalizableCommand;
import Commands.SerializzatoreCommand;
import Commands.SourceCommand;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author ludovicorusso
 */
public class guiCommand extends javax.swing.JFrame {
    private SourceCommand sc;
    private PersonalizableCommand p;
    private DefaultCommand dc;
    private SerializzatoreCommand sercommand;
    /**
     * Creates new form guiCommand
     */
    public guiCommand() throws IOException  {
        initComponents();
        sc=new SourceCommand();
        p=new PersonalizableCommand(0,0,0,0,0);
        sercommand=new SerializzatoreCommand();
        dc=new DefaultCommand();
        if(sc.getTypeCommand()){
            p=sc.getPersonalizzable();
            textJump.setText(KeyEvent.getKeyText(p.getJump()));
            textBasicAttack.setText(KeyEvent.getKeyText(p.getAttackB()));
            textSpecialAttack.setText(KeyEvent.getKeyText(p.getAttackS()));
            textDx.setText(KeyEvent.getKeyText(p.getDx()));
            textSx.setText(KeyEvent.getKeyText(p.getSx()));            
        }
        else{
            dc=sc.getDefault();
            textJump.setText(KeyEvent.getKeyText(dc.getJump()));
            textBasicAttack.setText(KeyEvent.getKeyText(dc.getAttackB()));
            textSpecialAttack.setText(KeyEvent.getKeyText(dc.getAttackS()));
            textDx.setText(KeyEvent.getKeyText(dc.getDx()));
            textSx.setText(KeyEvent.getKeyText(dc.getSx())); 
            p.setJump(dc.getJump());
            p.setDx(dc.getDx());
            p.setSx(dc.getSx());
            p.setAttack_b(dc.getAttackB());
            p.setAttack_s(dc.getAttackS());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textJump = new java.awt.TextField();
        labelJump = new java.awt.Label();
        textDx = new java.awt.TextField();
        labelDx = new java.awt.Label();
        textSx = new java.awt.TextField();
        labelSx = new java.awt.Label();
        textBasicAttack = new java.awt.TextField();
        labelAttack_b = new java.awt.Label();
        textSpecialAttack = new java.awt.TextField();
        labelSpecialAttack = new java.awt.Label();
        button1 = new java.awt.Button();
        btnRestore = new java.awt.Button();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textJump.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        textJump.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textJumpKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textJumpKeyTyped(evt);
            }
        });
        getContentPane().add(textJump, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 118, -1));

        labelJump.setFont(new java.awt.Font("Papyrus", 1, 13)); // NOI18N
        labelJump.setText("Jump");
        getContentPane().add(labelJump, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, -1, -1));

        textDx.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        textDx.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textDxKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textDxKeyTyped(evt);
            }
        });
        getContentPane().add(textDx, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 118, -1));

        labelDx.setFont(new java.awt.Font("Papyrus", 1, 13)); // NOI18N
        labelDx.setText("Dx");
        getContentPane().add(labelDx, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, -1));

        textSx.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        textSx.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textSxKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textSxKeyTyped(evt);
            }
        });
        getContentPane().add(textSx, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 118, -1));

        labelSx.setFont(new java.awt.Font("Papyrus", 1, 13)); // NOI18N
        labelSx.setText("Sx");
        getContentPane().add(labelSx, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, 20));

        textBasicAttack.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        textBasicAttack.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textBasicAttackKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textBasicAttackKeyTyped(evt);
            }
        });
        getContentPane().add(textBasicAttack, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 118, -1));

        labelAttack_b.setFont(new java.awt.Font("Papyrus", 1, 13)); // NOI18N
        labelAttack_b.setText("Basic Attack");
        getContentPane().add(labelAttack_b, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, -1));

        textSpecialAttack.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        textSpecialAttack.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textSpecialAttackKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textSpecialAttackKeyTyped(evt);
            }
        });
        getContentPane().add(textSpecialAttack, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 118, -1));

        labelSpecialAttack.setFont(new java.awt.Font("Papyrus", 1, 13)); // NOI18N
        labelSpecialAttack.setText("Special Attack");
        getContentPane().add(labelSpecialAttack, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));

        button1.setBackground(new java.awt.Color(0, 66, 0));
        button1.setFont(new java.awt.Font("Papyrus", 1, 13)); // NOI18N
        button1.setForeground(new java.awt.Color(255, 255, 255));
        button1.setLabel("Return");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        getContentPane().add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, -1, -1));

        btnRestore.setBackground(new java.awt.Color(0, 66, 0));
        btnRestore.setFont(new java.awt.Font("Papyrus", 1, 13)); // NOI18N
        btnRestore.setForeground(new java.awt.Color(255, 255, 255));
        btnRestore.setLabel("Restore");
        btnRestore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestoreActionPerformed(evt);
            }
        });
        getContentPane().add(btnRestore, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/bg.png"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(408, 321));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textJumpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textJumpKeyTyped
       if(textJump.getText().length()>=1) //Definisce il metodo per consumare un inserimento alla volta;
           evt.consume();
           
    }//GEN-LAST:event_textJumpKeyTyped

    private void textBasicAttackKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textBasicAttackKeyTyped
        if(textBasicAttack.getText().length()>=1)
           evt.consume();
        
    }//GEN-LAST:event_textBasicAttackKeyTyped

    private void textSpecialAttackKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textSpecialAttackKeyTyped
          if(textSpecialAttack.getText().length()>=1)
            evt.consume();
    }//GEN-LAST:event_textSpecialAttackKeyTyped

    private void textDxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textDxKeyTyped
          if(textDx.getText().length()>=1)
            evt.consume();
    }//GEN-LAST:event_textDxKeyTyped

    private void textSxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textSxKeyTyped
           if(textSx.getText().length()>=1)
            evt.consume();
    }//GEN-LAST:event_textSxKeyTyped

    private void textJumpKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textJumpKeyPressed
        try {
            p.setJump(evt.getKeyCode());
            textJump.setText(KeyEvent.getKeyText(p.getJump()));
            sercommand.save(p);
        } catch (IOException ex) {
            Logger.getLogger(guiCommand.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_textJumpKeyPressed

    private void textBasicAttackKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textBasicAttackKeyPressed
       try {
            p.setAttack_b(evt.getKeyCode());
            textBasicAttack.setText(KeyEvent.getKeyText(p.getAttackB()));
            sercommand.save(p);
        } catch (IOException ex) {
            Logger.getLogger(guiCommand.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_textBasicAttackKeyPressed

    private void textSpecialAttackKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textSpecialAttackKeyPressed
         try {
            p.setAttack_s(evt.getKeyCode());
            textSpecialAttack.setText(KeyEvent.getKeyText(p.getAttackS()));
            sercommand.save(p);
        } catch (IOException ex) {
            Logger.getLogger(guiCommand.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_textSpecialAttackKeyPressed

    private void textDxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textDxKeyPressed
        try {
            p.setDx(evt.getKeyCode());
            textDx.setText(KeyEvent.getKeyText(p.getDx()));
            sercommand.save(p);
        } catch (IOException ex) {
            Logger.getLogger(guiCommand.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_textDxKeyPressed

    private void textSxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textSxKeyPressed
         try {
            p.setSx(evt.getKeyCode());
            textSx.setText(KeyEvent.getKeyText(p.getSx()));
            sercommand.save(p);
        } catch (IOException ex) {
            Logger.getLogger(guiCommand.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_textSxKeyPressed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        MainGame.main(null);
        this.setVisible(false);
    }//GEN-LAST:event_button1ActionPerformed

    private void btnRestoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestoreActionPerformed
        File Command=new File("src/Resources/personalizzablecommand.dat");
        Command.delete();
        textJump.setText(KeyEvent.getKeyText(dc.getJump()));
        textBasicAttack.setText(KeyEvent.getKeyText(dc.getAttackB()));
        textSpecialAttack.setText(KeyEvent.getKeyText(dc.getAttackS()));
        textDx.setText(KeyEvent.getKeyText(dc.getDx()));
        textSx.setText(KeyEvent.getKeyText(dc.getSx()));
        PersonalizableCommand perco=new PersonalizableCommand(dc.getJump(),dc.getDx(),dc.getSx(),dc.getAttackB(),dc.getAttackS());
        try {
            sercommand.save(perco);
        } catch (IOException ex) {
            Logger.getLogger(guiCommand.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRestoreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                try {
                    new guiCommand().setVisible(true);
                    
                } catch (IOException ex) {
                    Logger.getLogger(guiCommand.class.getName()).log(Level.SEVERE, null, ex);
                }
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnRestore;
    private java.awt.Button button1;
    private javax.swing.JLabel jLabel1;
    private java.awt.Label labelAttack_b;
    private java.awt.Label labelDx;
    private java.awt.Label labelJump;
    private java.awt.Label labelSpecialAttack;
    private java.awt.Label labelSx;
    private java.awt.TextField textBasicAttack;
    private java.awt.TextField textDx;
    private java.awt.TextField textJump;
    private java.awt.TextField textSpecialAttack;
    private java.awt.TextField textSx;
    // End of variables declaration//GEN-END:variables
}
